logging:
  file:
    path: /var/log/sakila
  level:
    boot:
      spring:
        controller: DEBUG
    root: INFO
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.jgzl.po
server:
  port: 8080
spring:
  activiti:
    check-process-definitions: true
    database-schema-update: true
    history-level: full
    process-definition-location-prefix: classpath:/process/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/activiti
    username: root